image: golang:1.13

stages:
  - test
  - build-binary
  - build-image

test:
  stage: test
  script:
    - make test

lint:
  stage: test
  script:
    - make lint

build-binary-alpine:
  image: golang:1.13-alpine
  stage: build-binary
  only:
    refs:
      - branches
      - tags
  artifacts:
    paths:
      - bin
  script:
    - go build -o bin/dblab-server-alpine ./cmd/database-lab/main.go
    - go build -o bin/dblab-alpine ./cmd/cli/main.go

build-binary-generic:
  stage: build-binary
  only:
    refs:
      - branches
      - tags
  artifacts:
    paths:
      - bin
  script:
    - make build-generic

.job_template: &build_image_definition
  image: docker:19
  stage: build-image
  artifacts:
    paths:
      - bin
  services:
    - docker:dind
  script:
    - apk update && apk upgrade && apk add --no-cache bash # TODO(anatoly): Remove dependency.
    - bash ./scripts/ci_docker_build_push.sh

.only_var_template: &only_tag_release
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^[0-9.]+$/

.only_var_template: &only_tag_rc
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^[0-9.]+[\-_]*[a-zA-Z]+[a-zA-Z0-9.\-_]*[a-zA-Z0-9]+$/

.only_var_template: &only_master
  only:
    - master

.only_var_template: &only_feature
  only:
    refs:
      - branches
    variables:
      - $CI_COMMIT_REF_SLUG != "master"

build-image-feature-server:
  <<: *build_image_definition
  <<: *only_feature
  variables:
    REGISTRY_USER: "${CI_REGISTRY_USER}"
    REGISTRY_PASSWORD: "${CI_REGISTRY_PASSWORD}"
    REGISTRY: "${CI_REGISTRY}"
    DOCKER_FILE: "Dockerfile.dblab-server"
    DOCKER_NAME: "registry.gitlab.com/postgres-ai/database-lab/dblab-server"
    TAGS: "${DOCKER_NAME}:${CI_COMMIT_REF_SLUG}"
  before_script:
    - cp ./bin/dblab-server-alpine ./bin/dblab-server

build-image-feature-client:
  <<: *build_image_definition
  <<: *only_feature
  variables:
    REGISTRY_USER: "${CI_REGISTRY_USER}"
    REGISTRY_PASSWORD: "${CI_REGISTRY_PASSWORD}"
    REGISTRY: "${CI_REGISTRY}"
    DOCKER_FILE: "Dockerfile.dblab"
    DOCKER_NAME: "registry.gitlab.com/postgres-ai/database-lab/dblab"
    TAGS: "${DOCKER_NAME}:${CI_COMMIT_REF_SLUG}"
  before_script:
    - cp ./bin/dblab-alpine ./bin/dblab

build-image-feature-client-extended:
  <<: *build_image_definition
  <<: *only_feature
  variables:
    REGISTRY_USER: "${CI_REGISTRY_USER}"
    REGISTRY_PASSWORD: "${CI_REGISTRY_PASSWORD}"
    REGISTRY: "${CI_REGISTRY}"
    DOCKER_FILE: "Dockerfile.dblab-extended"
    DOCKER_NAME: "registry.gitlab.com/postgres-ai/database-lab/dblab-extended"
    TAGS: "${DOCKER_NAME}:${CI_COMMIT_REF_SLUG}"
  before_script:
    - cp ./bin/dblab-linux-amd64 ./bin/dblab

build-image-master-server:
  <<: *build_image_definition
  <<: *only_master
  variables:
    DOCKER_FILE: "Dockerfile.dblab-server"
    DOCKER_NAME: "registry.gitlab.com/postgres-ai/database-lab/dblab-server"
    TAGS: "${DOCKER_NAME}:master,${DOCKER_NAME}:master-${CI_COMMIT_SHORT_SHA}"
  before_script:
    - cp ./bin/dblab-server-alpine ./bin/dblab-server

build-image-master-client:
  <<: *build_image_definition
  <<: *only_master
  variables:
    DOCKER_FILE: "Dockerfile.dblab"
    DOCKER_NAME: "registry.gitlab.com/postgres-ai/database-lab/dblab"
    TAGS: "${DOCKER_NAME}:master,${DOCKER_NAME}:master-${CI_COMMIT_SHORT_SHA}"
  before_script:
    - cp ./bin/dblab-alpine ./bin/dblab

build-image-latest-server:
  <<: *build_image_definition
  <<: *only_tag_release
  variables:
    REGISTRY_USER: "${DH_CI_REGISTRY_USER}"
    REGISTRY_PASSWORD: "${DH_CI_REGISTRY_PASSWORD}"
    REGISTRY: "${DH_CI_REGISTRY}"
    DOCKER_FILE: "Dockerfile.dblab-server"
    DOCKER_NAME: "postgresai/dblab-server"
    TAGS: "${DOCKER_NAME}:latest,${DOCKER_NAME}:${CI_COMMIT_TAG}"
  before_script:
    - cp ./bin/dblab-server-alpine ./bin/dblab-server

build-image-latest-client:
  <<: *build_image_definition
  <<: *only_tag_release
  variables:
    REGISTRY_USER: "${DH_CI_REGISTRY_USER}"
    REGISTRY_PASSWORD: "${DH_CI_REGISTRY_PASSWORD}"
    REGISTRY: "${DH_CI_REGISTRY}"
    DOCKER_FILE: "Dockerfile.dblab"
    DOCKER_NAME: "postgresai/dblab"
    TAGS: "${DOCKER_NAME}:latest,${DOCKER_NAME}:${CI_COMMIT_TAG}"
  before_script:
    - cp ./bin/dblab-alpine ./bin/dblab

build-image-rc-server:
  <<: *build_image_definition
  <<: *only_tag_rc
  variables:
    REGISTRY_USER: "${DH_CI_REGISTRY_USER}"
    REGISTRY_PASSWORD: "${DH_CI_REGISTRY_PASSWORD}"
    REGISTRY: "${DH_CI_REGISTRY}"
    DOCKER_FILE: "Dockerfile.dblab-server"
    DOCKER_NAME: "postgresai/dblab-server"
    TAGS: "${DOCKER_NAME}:${CI_COMMIT_TAG}"
  before_script:
    - cp ./bin/dblab-server-alpine ./bin/dblab-server

build-image-rc-client:
  <<: *build_image_definition
  <<: *only_tag_rc
  variables:
    REGISTRY_USER: "${DH_CI_REGISTRY_USER}"
    REGISTRY_PASSWORD: "${DH_CI_REGISTRY_PASSWORD}"
    REGISTRY: "${DH_CI_REGISTRY}"
    DOCKER_FILE: "Dockerfile.dblab"
    DOCKER_NAME: "postgresai/dblab"
    TAGS: "${DOCKER_NAME}:${CI_COMMIT_TAG}"
  before_script:
    - cp ./bin/dblab-alpine ./bin/dblab

build-image-swagger-latest:
  <<: *build_image_definition
  <<: *only_tag_release
  variables:
    DOCKER_FILE: "Dockerfile.swagger-ui"
    DOCKER_NAME: "registry.gitlab.com/postgres-ai/database-lab/dblab-swagger-ui"
    TAGS: "${DOCKER_NAME}:latest"
