# Copy the following to: ./configs/config.yaml

server:
  verificationToken: "xxx"
  port: 3000

provision:
  mode: "zfs"
  zfs:
    pool: "dblab_pool"
    portPool:
      from: 6000
      to: 6100
    mountDir: /var/lib/dblab/clones
    unixSocketDir: /var/lib/dblab/sockets
    snapshotFilterSuffix: "_pre"
    dockerImage: "postgres:12-alpine"
  pgDataSubdir: "/"
  pgVersion: "12"

cloning:
  mode: "base"
  accessHost: "localhost"
  idleTime: 0 # Minutes. 0 - means disable automatic deletion.

debug: true
