# Copy the following to: ./configs/config.yaml

server:
  verificationToken: "xxx"
  port: 3000

provision:
  mode: "zfs"
  zfs:
    pool: "dblab_pool"
    portPool:
      from: 6000
      to: 6100
    mountDir: /var/lib/postgresql/dblab/clones
    logsDir: /var/lib/postgresql/dblab/logs
    snapshotFilterSuffix: "_pre"
  pgBindir: "/usr/lib/postgresql/12/bin"
  pgDataSubdir: "/"
  pgVersion: "12"

cloning:
  mode: "base"
  accessHost: "localhost"
  autoDelete: true
  idleTime: 120

debug: true
