# Copy the following to: ./configs/config.yaml

# Database Lab server configuration.
server:
  verificationToken: "secret_token"

  # The host which the Database Lab server accepts HTTP connections from. 
  # By default: "127.0.0.1", accepts only local connections. Use an empty string to accept all connections.
  host: "127.0.0.1"

  # HTTP server port. By default: 2345.
  port: 2345

global:
  engine: postgres
  dataDir: /var/lib/dblab
  dockerImage: "postgres:12-alpine"

# Postgres.ai Platform integration.
platform:
  # API URL.
  url: "https://postgres.ai/api/general"

  # Token for authorization in Platform API. This token can be obtained in Postgres.ai Console:
  # see the corresponding organization, "Access tokens" in the left menu.
  accessToken: "platform_access_token"

  # Enable authorization with personal tokens of the organization's members.
  enablePersonalTokens: false

provision:
  # Provision mode to use.
  mode: "local"

  # Subdir where PGDATA located relative to the pool root dir.
  pgDataSubdir: "/"

  # Username that will be used for Postgres management connections.
  # The user should exist.
  pgMgmtUsername: "postgres"

  # "Local" mode related parameters.
  local:
    # Which thin-clone managing module to use.
    # Available options: "zfs", "lvm".
    thinCloneManager: "zfs"

    # Name of your pool (in the case of ZFS) or volume group
    # with logic volume name (e.g. "dblab_vg/pg_lv", in the case of LVM).
    pool: "dblab_pool"

    # Pool of ports for Postgres clones.
    portPool:
      from: 6000
      to: 6100

    # Clones PGDATA mount directory.
    mountDir: /var/lib/dblab/clones

    # Unix sockets directory for secure connection to Postgres clones.
    unixSocketDir: /var/lib/dblab/sockets

    # Snapshots with the suffix will not be accessible to use for cloning.
    snapshotFilterSuffix: "_pre"

    # Database Lab provisions thin clones using Docker containers, we need
    # to specify which Postgres Docker image is to be used when cloning.
    # The default is the extended Postgres image built on top of the official Postgres image
    # (See https://hub.docker.com/repository/docker/postgresai/extended-postgres).
    # Any custom or official Docker image that runs Postgres with PGDATA located
    # in "/var/lib/postgresql/pgdata" directory. Our Dockerfile
    # (See https://gitlab.com/postgres-ai/database-lab/snippets/1932037)
    # is recommended in case if customization is needed.
    dockerImage: "postgresai/extended-postgres:12"

    # Use sudo for ZFS/LVM and Docker commands if Database Lab server running
    # outside a container.
    useSudo: false

cloning:
  mode: "base"

  # Host which will be specified in clone connection info.
  accessHost: "localhost"

  # Auto-delete clones after the specified minutes of inactivity.
  # 0 - disable automatic deletion.
  maxIdleMinutes: 120

retrieval:
  stages:
    - initialize

  spec:
    initialize:
      jobs:
#        - name: logical-restore
#          options:
#            dumpFile: /tmp/db.dump
#            forceInit: false
#            dbName: test
#            partial:
#              tables:
#                - test
        - name: physical-restore
          options:
            tool: walg
            dockerImage: "postgresai/sync-instance:12"
            envs:
              WALG_GS_PREFIX: "gs://{BUCKET}/{SCOPE}"
            walg:
              storage: gcs
              backupName: LATEST
              credentialsFile: /tmp/sa.json # optional

debug: true
